'use strict';
//
// serendipity.js — one unexpected cross-project connection per day.
//
// GET /api/serendipity — returns { connection: { a, b, link, text, seed }, date }
//
// The engine takes two random projects/panels that have data, and finds an
// unexpected connection between them. It's not a recommendation engine —
// it's a creative prompt. The connection is generated by Ollama from the
// project descriptions and their current state, or by a simple template
// system when Ollama is down.
//
// The seed is stored for the day so the same connection shows up all day
// (you don't get a different one on every refresh — that would be noise,
// not serendipity).
const express = require('express');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');

const router = express.Router();

// The workspace vocabulary has ONE owner: server/routes/projects.js (M272). This module
// used to keep its own ten-name copy with hand-written descriptions — a second place the
// truth lived, and it had already drifted (no Fallow, no Garage, no high-society). The
// owner's `note` serves as the description; a pairing prompt needs nothing richer.
const { PROJECTS: OWNED } = require('./projects');
const PROJECTS = OWNED.map((p) => ({ name: p.name, desc: p.note || p.track || '' }));

const CONNECTION_TEMPLATES = [
  '{a} meets {b}: what would the product look like?',
  'If {a} and {b} shared one feature, what would it be?',
  'What if {a}\'s audience also wanted {b}?',
  'Combine {a}\'s approach with {b}\'s platform.',
  'What does {a} know that {b} could use?',
  'If {b} were a mode inside {a}, what would it do?',
  'What would happen if {a}\'s constraints were applied to {b}?',
  'Build a bridge: one thing from {a} that solves a problem in {b}.',
  'What if the user of {a} is also the maker of {b}?',
  'If {a} and {b} had a baby, what would its name be?',
];

// Deterministic daily seed: same day = same connection
function dailySeed() {
  const today = new Date().toISOString().slice(0, 10);
  let h = 0;
  for (const c of today) h = (h * 31 + c.charCodeAt(0)) & 0x7fffffff;
  return h;
}

function pick(arr, seed) {
  return arr[seed % arr.length];
}

// The template-based half of the connection: deterministic, synchronous, no Ollama.
// This is what the morning briefing reads (via dailyConnection()) — the briefing
// calls sources through their exported function, never a live model, so it stays
// fast even when Ollama is down. The GET route below layers the optional Ollama
// enrichment on top of this same base for the panel.
function dailyConnection() {
  const seed = dailySeed();
  const a = pick(PROJECTS, seed);
  const b = pick(PROJECTS, seed >> 8);

  // Make sure a != b
  let bFinal = b;
  if (a.name === b.name) {
    bFinal = PROJECTS[((seed >> 8) + 1) % PROJECTS.length];
  }

  const template = pick(CONNECTION_TEMPLATES, seed >> 16);
  const text = template
    .replace(/\{a\}/g, a.name)
    .replace(/\{b\}/g, bFinal.name);

  return {
    a, bFinal, template, text, seed,
    date: new Date().toISOString().slice(0, 10),
  };
}

router.get('/', async (req, res) => {
  const { a, bFinal, template, text, seed } = dailyConnection();

  // Try Ollama for a richer connection
  let richText = text;
  let ollamaUsed = false;
  try {
    const ollama = require('../ollama');
    const prompt = `You are a creative strategist. Find an unexpected, specific connection between these two projects:

Project A: ${a.name} — ${a.desc}
Project B: ${bFinal.name} — ${bFinal.desc}

Write ONE sentence (max 150 chars) that connects them in a surprising way.
Be specific and concrete, not generic. Return ONLY the sentence.`;

    const response = await ollama.ask({
      model: 'qwen3.5:4b',
      user: prompt,
      timeoutMs: 30000,
    });
    if (response && response.ok && response.text && response.text.trim().length > 10) {
      richText = response.text.trim().slice(0, 200);
      ollamaUsed = true;
    }
  } catch {
    // Fallback to template
  }

  res.json({
    connection: {
      a: a.name,
      aDesc: a.desc,
      b: bFinal.name,
      bDesc: bFinal.desc,
      text: richText,
      template: ollamaUsed ? null : text,
      ollama: ollamaUsed,
    },
    seed,
    date: new Date().toISOString().slice(0, 10),
  });
});

module.exports = router;
module.exports.dailyConnection = dailyConnection;