//
// dispatch.js — which agent, which model, how much effort, for one work item.
//
// Owner instruction, 19 Aug 2026: "Find a way to append each task a model and effort to use —
// the goal is to use the right tool for the right job and keep token expenditure minimal."
//
// DERIVED, NEVER TYPED, and that is the whole design. A `model` column somebody has to fill in
// on every item is a surface he must feed, which the workspace gate rejects outright — and it
// would be wrong within a week, because the item changes and the stored answer does not. This
// reads the fields an item already carries (kind, priority, cluster, project, the DET/LOC/FRO
// tier, and its own text) and returns a recommendation with the reason attached.
//
// IT IS A DECISION TABLE, NOT A SCORE. No weights, no points, no composite number. A score
// built from coefficients I chose is the one figure nobody can audit, and this project has a
// standing rule against presenting one as a measurement. Every rule below reads as a sentence
// you can agree or disagree with, and the FIRST matching rule wins so the outcome is traceable
// to one line rather than to an accumulation.
//
// THE CHEAPEST THING THAT CAN DO THE JOB IS THE DEFAULT. Escalation must be earned by a
// property of the task; de-escalation is free. The measured precedent is this project's own:
// on the real categorisation job, deterministic rules did 95.3% and the model 4.7%. So the
// first question is never "which model" but "does this need a model at all".
'use strict';

// What is actually available here, so a recommendation cannot name something that does not
// exist. Costs are ORDINAL, not prices — cheap/mid/dear — because I do not have per-token
// figures for a ChatGPT subscription and an invented number would be worse than an ordering.
const AGENTS = {
  script: { engine: 'none', cost: 'free', what: 'a .cjs script or a SQL query — no model at all' },
  local: { engine: 'ollama', cost: 'free', what: 'qwen3.5:9b, on this machine, private' },
  haiku: { engine: 'claude', cost: 'cheap', what: 'Claude Haiku 4.5' },
  sonnet: { engine: 'claude', cost: 'mid', what: 'Claude Sonnet 5' },
  opus: { engine: 'claude', cost: 'dear', what: 'Claude Opus 5' },
  codex: { engine: 'codex', cost: 'subscription', what: 'Codex CLI, gpt-5.6-terra, on the owner\'s plan' },
};

const EFFORT = ['low', 'medium', 'high', 'xhigh', 'max'];

// Text signals. Deliberately narrow: a word that appears in half the backlog is not a signal,
// it is noise wearing a regex.
const IRREVERSIBLE = /\bmigrat|schema|drop table|delete|credential|secret|api key|token|rotate|publish|post to|deploy|git history|force[- ]push|backup\b/i;
const AMBIGUOUS = /\binvestigat|diagnos|why |root cause|unclear|unknown|figure out|work out|research|explore|decide|design\b/i;
const MECHANICAL = /\brename|typo|wording|copy|label|comment|format|lint|bump|tidy|move the|spelling\b/i;

function has(item, re) {
  return re.test(`${item.title || ''} ${item.rationale || ''}`);
}

/**
 * @returns {{agent, model, engine, effort, cost, why, escalateIf, rule}}
 */
function dispatch(item = {}) {
  const kind = String(item.kind || '').toLowerCase();
  const pri = String(item.priority || '').toUpperCase();
  const cluster = String(item.cluster || '').toLowerCase();
  const text = `${item.title || ''} ${item.rationale || ''}`;

  const out = (rule, agent, effort, why, escalateIf) => ({
    rule,
    agent,
    model: agent,
    engine: AGENTS[agent].engine,
    cost: AGENTS[agent].cost,
    what: AGENTS[agent].what,
    effort,
    why,
    escalateIf: escalateIf || null,
  });

  // ---------------------------------------------------------------- hard rules first
  // These are not preferences and not economies. They come from decisions the owner made,
  // and a cheaper answer does not override them.

  if (cluster === 'wellbeing' || /wellbeing/i.test(text)) {
    return out('wellbeing is never a model', 'script', 'low',
      'Nothing in the wellbeing module may be generated by a model — not prose, not a pattern, not a risk score. That is fixed policy, not a cost decision.',
      'Never. If it cannot be done deterministically it is not done.');
  }

  if (/\.css\b|stylesheet|contrast|spacing|palette|theme|visual|layout/i.test(text)) {
    return out('CSS belongs to Codex', 'codex', 'medium',
      'Every stylesheet in this project is Codex\'s by the owner\'s decision of 19 Aug (#18). No other agent edits them; a session that needs a style change files it for Codex.',
      'A design-system change to shared.css or shell.css reaches all 21 panels — raise the effort and check every panel, not the one you were looking at.');
  }

  if (kind === 'review' || /\breview\b/i.test(item.title || '')) {
    const authorEngine = String(item.author_engine || 'unknown');
    const reviewer = authorEngine === 'codex' ? 'opus' : 'codex';
    return out('a review must not share the author\'s engine', reviewer, 'high',
      `The author's engine is ${authorEngine}, so the reviewer must be the other one. A checker sharing the author's assumptions confirms the author's bugs, which is the whole reason a second engine exists here (#16).`,
      'If no independent engine is available the review is REFUSED and recorded as not reviewed — never run same-engine and never recorded as a pass.');
  }

  // ---------------------------------------------------------- does it need a model at all
  if (String(item.owner || '').toUpperCase() === 'DET' && !has(item, AMBIGUOUS)) {
    return out('a deterministic answer exists', 'script', 'low',
      'Already tagged DET, and nothing in the text says the diagnosis is unknown. A deterministic answer is exact, auditable, reproducible by inspection, and free. Measured here: rules did 95.3% of the real categorisation job, the model 4.7%.',
      'If the first attempt shows the rule cannot be stated exactly, that is the signal to escalate — not the fact that writing it is dull.');
  }

  if (String(item.owner || '').toUpperCase() === 'LOC') {
    return out('tagged for the local model', 'local', 'low',
      'Low-stakes, reviewable, structurally constrained — the binding conditions for Ollama. It is free and private, so volume argues against the frontier tier, never against this one.',
      'It must degrade to "not done, do it yourself" when Ollama is not running, and must never emit a figure.');
  }

  // ------------------------------------------------------------------- now cost vs risk
  // Effort scales with what a wrong answer COSTS, not with how interesting the task is.

  if (pri === 'P0') {
    return out('P0 never economises', 'opus', 'high',
      'Active data loss, a live security hole, or a defect invalidating work in flight. The cheapest model is not the cheapest outcome here — the cost of a wrong answer dwarfs the cost of the tokens.',
      'Already at the top of the ordinary range. Go to xhigh only if the first pass cannot reproduce the failure.');
  }

  if (has(item, IRREVERSIBLE)) {
    return out('irreversible work', 'opus', 'high',
      'This touches something that cannot be undone by editing a file back — a migration, a credential, git history, or something published. Migrations here are append-only by rule; a published post cannot be recalled.',
      'Stay at high. The saving from a cheaper model is one task; the cost of a bad migration is the ledger.');
  }

  if (has(item, AMBIGUOUS)) {
    return out('the diagnosis is unknown', 'opus', 'high',
      'The task is to work out WHAT is wrong, not to apply a known fix. That is where a weaker model spends more tokens than a stronger one by exploring in the wrong direction, so the cheap choice is usually the expensive one.',
      'Once the diagnosis is written down, the FIX is usually a separate, much cheaper task. Split it rather than carrying high effort through the whole thing.');
  }

  if (has(item, MECHANICAL) && (pri === 'P3' || kind === 'chore')) {
    return out('mechanical and specified', 'haiku', 'low',
      'A rename, a label, a wording change: the answer is stated in the task and the work is applying it. Reversible in one commit, and nothing derives from it.',
      'If it turns out to touch more files than expected, stop and re-dispatch — breadth is the signal, not difficulty.');
  }

  if (kind === 'bug' && !has(item, AMBIGUOUS)) {
    return out('a bug with a known cause', 'sonnet', 'medium',
      'A reproduction and a cause are already recorded, so the work is implementing and verifying a fix rather than finding one.',
      'If the reproduction does not reproduce, it is no longer this task — it is a diagnosis task, and that is opus/high.');
  }

  if (pri === 'P3') {
    return out('low stakes, ordinary work', 'sonnet', 'low',
      'P3 is cosmetic or marginal by definition. Reversible, nothing derives from it, and no figure depends on it.',
      'Raise it only if the change turns out to touch a shared file.');
  }

  return out('ordinary implementation', 'sonnet', 'medium',
    'A clear enough specification, reversible, and blast radius limited to what it names. The middle of the range is the honest default when nothing about the task argues for either end.',
    'Escalate on discovering ambiguity, irreversibility, or that it touches a shared file. Any of those three, not a feeling that it is hard.');
}

// The whole table, for reading rather than for calling. A router nobody can audit is a router
// nobody should trust.
function explain() {
  const cases = [
    ['a wellbeing pattern', { cluster: 'Wellbeing' }],
    ['panel spacing is wrong', { title: 'fix spacing in the budget panel css' }],
    ['review commit abc123', { kind: 'review', title: 'review abc123', author_engine: 'claude' }],
    ['categorise known merchants', { owner: 'DET', title: 'add merchant rules' }],
    ['a P0 data-loss defect', { priority: 'P0', title: 'rows are being dropped on import' }],
    ['add a migration', { priority: 'P2', title: 'add a schema migration for handover items' }],
    ['why is the bot dying', { priority: 'P2', title: 'investigate why the bot dies at night' }],
    ['rename a nav label', { priority: 'P3', kind: 'chore', title: 'rename the nav label' }],
    ['a bug with a repro', { priority: 'P2', kind: 'bug', title: 'panel shows 0 when the API is down' }],
    ['ordinary feature', { priority: 'P2', kind: 'feature', title: 'add a filter to the board' }],
  ];
  return cases.map(([label, item]) => ({ label, ...dispatch(item) }));
}

module.exports = { dispatch, explain, AGENTS, EFFORT };
